Implemented gxtarget-info

diff --git a/gxmount b/gxmount
--- a/gxmount
+++ b/gxmount
@@ -4,19 +4,23 @@
 
 source "${HOME}/.gxrc"
 
-set -e
-
 if [ -z $1 ]; then
     echo "./gxmount <ipaddr>"
     exit 1
 fi
 
-HOSTNAME=$(ssh $1 -o PasswordAuthentication=no hostname)
+INFO_STR=$(ssh $1 -o PasswordAuthentication=no gxtarget-info)
 
-if [ -z $HOSTNAME ]; then
-    echo "SSH Connection Failed. Make sure that you have permission to log into this computer, and that you have ssh keys set up!"
+if [ -z $INFO_STR ]; then
+    echo "Mounting Failed. Make sure that you have permission to log into this computer, and that you have ssh keys set up! Also make sure that galaxy scripts are installed and that 'gxtarget-info' is in path"
     exit 1
 fi
+
+set -e
+
+HOSTNAME=$(echo $INFO_STR | cut -d";" -f1)
+
+REMOTE_GX_DIR=$(echo $INFO_STR | cut -d";" -f3)
 
 # Mount the filesystem
 
@@ -31,7 +35,5 @@ sshfs $1:/ $GALAXY_DIR/tmp/mnt/$MNT_ID &
 _pid=$! # Save the sshfs PID, since sometimes it gets stuck
 
 ln -s $GALAXY_DIR/tmp/mnt/$MNT_ID $GALAXY_DIR/mnt/$HOSTNAME
-
-REMOTE_GX_DIR="$GALAXY_DIR/mnt/$HOSTNAME/home/$USER" # TODO Make this properly handle custom home paths
 
 echo "$HOSTNAME;$1;$MNT_ID;$_pid;$REMOTE_GX_DIR" >> $GALAXY_DIR/tmp/connections
