Implemented gxrunner-host, added env info

diff --git a/gxrunner-host b/gxrunner-host
--- a/gxrunner-host
+++ b/gxrunner-host
@@ -5,11 +5,30 @@
 source "${HOME}/.gxrc"
 
 if [ -z "$1" ]; then
-    echo "gxrunner-host <command_name>"
+    echo "gxrunner-host <ip_addr>"
     exit 1
 fi
 
-CMD_LINE=$(cat $GALAXY_DIR/config/commands | grep $1)
+if [ -z "$2" ]; then
+    echo "gxrunner-host <ip_addr> <command_name>"
+    exit 1
+fi
+
+# Get Hostname from connections file
+
+CONN_LINE=$(cat $GALAXY_DIR/tmp/connections | grep $1)
+
+HOSTNAME=$(echo $CONN_LINE | cut -d";" -f1)
+IP=$(echo $CONN_LINE | cut -d";" -f2)
+
+REMOTE_GX=$(echo $CONN_LINE | cut -d";" -f5) # Remote Galaxy Dir
+
+if [ -z "$HOSTNAME" ]; then
+    echo "Couldn't find hostname in connections. Was this computer mounted?"
+    exit 1
+fi
+
+CMD_LINE=$(cat $GALAXY_DIR/mnt/$HOSTNAME$REMOTE_GX/config/commands | grep $1)
 
 if [ -z "$CMD_LINE" ]; then
     echo "Command not found on this system"
@@ -31,10 +50,7 @@ fi
 DISPLAY_NUM=":0"
 
 if [ -n $USE_XPRA ]; then 
-    DISPLAY_NUM=$(xpra list | grep LIVE | cut -d":" -f2)
-    if [ -z "$DISPLAY_NUM"]; then
-        echo "Starting Xpra at :100..."
-        xpra start :100
-        DISPLAY_NUM=":100"
-    fi
+    DISPLAY_NUM=$DEFAULT_XPRA
 fi
+
+ssh $IP "bash -c gxrunner-target $CMD"
